#!/usr/bin/env node
// Generated by scripts/sync-skill-bundles.mjs. Edit the generator, not this file.
import { execFileSync, spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

let root = process.env.OPCHAIN_ROOT;
if (!root) {
  try {
    root = execFileSync('git', ['rev-parse', '--show-toplevel'], {
      cwd: process.cwd(), encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    root = process.cwd();
  }
}
const result = spawnSync(process.execPath, [
  fileURLToPath(new URL('./telemetry.runtime.mjs', import.meta.url)),
  ...process.argv.slice(2),
], { stdio: 'inherit', env: { ...process.env, OPCHAIN_ROOT: resolve(root) } });
if (result.error) console.error(result.error.message);
process.exit(result.status ?? 1);
